x = float(input('Uma distância em metros: '))
print('A medida de', x, 'm corresponde a')
print('{}km'. format(x / 1000))
print('{}hm'. format(x / 100))
print('{}dam'. format(x / 10))
print('{}dm'. format(x * 10))
print('{}cm'. format(x * 100))
print('{}mm'. format(x * 1000))